# Generated by Django 5.2.7 on 2025-10-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=120)),
                ('marca', models.CharField(max_length=120)),
                ('ano', models.CharField(max_length=4)),
                ('quilometragem', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('cor', models.CharField(max_length=50)),
                ('localizacao', models.CharField(max_length=255)),
                ('repassado', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('origem', models.CharField(choices=[('OLX', 'OLX'), ('WEBMOTORS', 'Webmotors'), ('MERCADO_LIVRE', 'Mercado Livre'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20)),
                ('autor_nome', models.CharField(max_length=120)),
                ('autor_telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'anuncios',
                'indexes': [models.Index(fields=['marca'], name='anuncios_marca_80eea0_idx'), models.Index(fields=['modelo'], name='anuncios_modelo_52e93b_idx'), models.Index(fields=['ano'], name='anuncios_ano_24bad9_idx'), models.Index(fields=['preco'], name='anuncios_preco_355f75_idx'), models.Index(fields=['quilometragem'], name='anuncios_quilome_9a0dcb_idx'), models.Index(fields=['origem'], name='anuncios_origem_252d96_idx')],
            },
        ),
    ]
