

services:
  backend:
    build:
      context: ./Buscarro/backend/app
    container_name: backend
    environment:
      - DJANGO_PROD_ENV=True
      - DJANGO_COMMENTS=True
      - POSTGRES_DB=django
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=liana
      - POSTGRES_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
      
    ports:
      - "8000:8000"
    networks:
      - backend-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
     - POSTGRES_DB=django
     - POSTGRES_PASSWORD=liana
     - POSTGRES_USER=postgres
    volumes:
     - postgres_data:/var/lib/postgresql/data
    expose:
     - "5432"
    networks:
     - backend-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./Buscarro/frontend
    container_name: frontend
    depends_on:
     - backend
    ports:
     - "5173:5173"
    networks:
     - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge
